### ISSUE TITLE
Multiple optional containers

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/injector#14]
What do you think about adding the ability to set multiple containers in the injector?

```php
class Injector {
    public function __construct(ContainerInterface $container, ContainerInterface ...$containers) {}
}

$injector = new Injector($container);
// or
$injector = new Injector($container1, $container2);
// or
$injector = new Injector(...$containers);
```

I know that i can take a composite container, but out of the box it will be easier.

In addition, the container itself may be a optional and multiple parameter.
```php
class Injector {
    public function __construct(ContainerInterface ...$containers) {}
}
```
It seems to me that this would be useful for those cases when the set of potential parameters is predetermined and the transfer of the container is already superfluous

**Comment by samdark** [comment]
I don't think we should implement it. It's rare use-case, there are composite containers available.
