### ISSUE TITLE
Better support for PHP 8

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/injector#15]
For better support for PHP 8, we should update the Injector code.

* Use `ReflectionType` instead of `ReflectionParameter::getClass()` and `ReflectionParameter::getType()`.
* Check that the Injector are working correctly with internal functions .

Links:
https://github.com/php/php-src/blob/00ef092335946d47817fa307f9cf570f236bc006/UPGRADING#L314
https://github.com/php/php-src/blob/00ef092335946d47817fa307f9cf570f236bc006/UPGRADING#L558

**Comment by samdark** [comment]
First of all, we need to run tests against PHP 8.
