### ISSUE TITLE
Supporting for php 8.1 (pure intersection types)

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/injector#61]
Need to update the Injector and tests
https://wiki.php.net/rfc/pure-intersection-types
Enums (just cover with tests)

**Comment by vjik** [comment]
We don't can get object from container by intersection types. Injector can use only explicitly passed parameters for arguments with intersection types.

**Comment by roxblnfk** [comment]
I mean Injector's ability to pass prepared unnamed arguments (without using Container).
Also we have [some code](https://github.com/yiisoft/injector/blob/d936d15e8a0c70d3486832ad75edf73688d4c309/src/ArgumentException.php#L52-L62) that prints method signatures. It should support intersected types.

**Comment by roxblnfk** [comment]
Last issue part is here: https://github.com/yiisoft/injector/issues/65
